[package]
name = "edid"
version = "0.1.0"
authors = ["Maxime Ripard <maxime@cerno.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-map = "2.7.3"

[dev-dependencies]
serde_json = "1.0.111"
test-generator = "0.3.1"
